#ifndef BOT_CHAT_DRIBBLE_POOL_H
#define BOT_CHAT_DRIBBLE_POOL_H

// Generic General openers. Not slotted to a live quest/mob — those stay in
// PickAmbientDribbleLine. Takes, not status. No slurs first. WotLK-era voice.
// Mix trash talk, arguments, jokes, memes, and salt so the room is not 200
// variants of the same quest complaint.

// 1198 mixed openers
inline char const* const kDribbleOpeners[] = {
    "uninstall wow pls",
    "close the game",
    "why do you people still play this",
    "this game is dying again",
    "blizz balance lmao",
    "blizz hates the player",
    "nerf paladins already",
    "buff horde for once",
    "alliance always camps",
    "horde cant pvp",
    "dks are easy mode",
    "ret pally is a joke",
    "hunters are braindead",
    "warlocks in every pug",
    "rogues only pvp",
    "mages ice lancing afk",
    "priests afk in the back",
    "this spec is faceroll",
    "cookie cutter builds everywhere",
    "pugs are a joke",
    "this pug is a wipefest",
    "wipes on trash again",
    "dont stand in fire challenge failed",
    "healers afk or what",
    "tanks pulling with their face",
    "stop pulling extra",
    "dps parsing gray",
    "someone ninja'd in my last run",
    "ninja paladin strikes again",
    "need on everything ninja",
    "this is why pugs suck",
    "lfm means look for ninja",
    "gold sellers in mail",
    "ah is a casino",
    "repair bill hates me",
    "vendor trash forever",
    "1 copper drops lmao",
    "grey as far as i can see",
    "mount gold is a trap",
    "flying is a gold sink",
    "lag is the real boss",
    "client froze again",
    "queue was a joke",
    "rubberbanding to dalaran",
    "dc in a boss pull classic",
    "loading screen simulator",
    "why do people afk at the fp",
    "afk in the inn again",
    "bio in a pug nice",
    "gkick that guy lmao",
    "kick the afk",
    "vote kick when",
    "carebears ruined pvp",
    "pvp in this bracket is dead",
    "arena is pay to queue",
    "wg is a zerg fest",
    "av is 40 mins of running",
    "eots is a meme",
    "wsg tunnel vision",
    "ganked at the fp again",
    "lowbies getting farmed",
    "honor farming noobs",
    "world pvp is dead",
    "this xpac is easy",
    "vanilla was better",
    "tbc was better",
    "they dumbed it down",
    "wrath is faceroll",
    "icc pugs already",
    "naxx pugs are a zoo",
    "ulduar people cant jump",
    "voa is a loot pinata",
    "toc is a waiting room",
    "stand in fire simulator",
    "move out of the swirl",
    "stack is a myth",
    "spread means stack here",
    "sheep the sheep",
    "sapped the healer",
    "hunter pet pulling towns",
    "feed your pet",
    "pet disappeared this game is broken",
    "out of ammo in a dungeon",
    "ammo is a tax",
    "durability is a scam",
    "reagents cost more than the run",
    "repair after one wipe",
    "why is walking still a thing",
    "no mounts till 30 still hurts",
    "boat to tb takes years",
    "zeppelins are a coin flip",
    "org is a maze",
    "sw is lag city",
    "dalaran is a gold sink",
    "where is the bank in dal",
    "underbelly is a trap",
    "lost in the sewers again",
    "mankrik still looking",
    "barrens chat never dies",
    "goldshire is a zoo",
    "stv is gank city",
    "if youre in stv you deserve it",
    "tarren mill vs southshore forever",
    "alterac is a parking lot",
    "wintergrasp when",
    "wg queue is instant nvm 20 min",
    "lfd pugs cant interrupt",
    "random dungeon is a coin flip",
    "heroic daily is a second job",
    "badges are a grind",
    "frost badges when",
    "emblem inflation",
    "tier is a lottery",
    "need rolling hunters",
    "greed on boe ninja",
    "disenchanter ninja",
    "loot council in a pug lmao",
    "ml is a tyrant",
    "this group has no cc",
    "sheep is optional apparently",
    "traps on cooldown forever",
    "misdirect into the pack",
    "heroism on trash",
    "bl on cooldown for adds",
    "tank has no mitigation",
    "dps racing threat",
    "warlock pulling with fear",
    "mage pulling with ae",
    "rogue vanished from the wipe",
    "priest died first again",
    "wipe on trash again",
    "first boss took 12 min",
    "this is a 5 man not icc",
    "we dont need a strat for trash",
    "watch a video",
    "parse later play now",
    "logs dont matter in pug",
    "recount is a religion",
    "meters dont heal",
    "threat meter when",
    "dbm is screaming",
    "turn off the addon spam",
    "quest helper is carrying",
    "lightheaded or get lost",
    "atlas or wander",
    "where are the quest marks",
    "this ui is from 2004",
    "default ui is a crime",
    "bartender or nothing",
    "weakauras is cheating nvm",
    "clickers in my melee",
    "keyboard turning warrior",
    "wasd only pally",
    "jumping every second hunter",
    "backpedal rogue",
    "strafes in a circle lmao",
    "camera in the floor",
    "max camera distance pls",
    "nameplates off on purpose",
    "who plays with music on",
    "disable ambient i beg",
    "this soundtrack slaps tho",
    "wrath music is the real tank",
    "login music hit different",
    "queued for a flight",
    "gryphon took the scenic route",
    "fp pathing is drunk",
    "dismounted in combat classic",
    "indoor mount when blizz",
    "cant mount in this cave",
    "swim speed is a joke",
    "underwater breathing tax",
    "hearth is on cooldown of course",
    "inn is the wrong one",
    "binded in the wrong city",
    "port to theramore why",
    "mage portal tax",
    "warlock summon club",
    "summoning stone is across the zone",
    "meeting stone unused",
    "lfg channel is dead",
    "trade is a gold spam",
    "lookingforgroup is a graveyard",
    "guild recruit spam",
    "pst for ginvite scams",
    "level 1 ginv",
    "social guild my foot",
    "raid guild that never raids",
    "we raid tue sun and never",
    "loot council friends",
    "dkp is a cult",
    "gdkp in wrath lmao",
    "gold buyers in icc",
    "boosted to 80",
    "heirlooms made this easy",
    "rested xp carrying me",
    "this grind is unpaid work",
    "xp per hour is a myth",
    "ding and log",
    "alt army",
    "too many alts",
    "bank alt has a better ui",
    "mail is full of vendor junk",
    "empty the mailbox challenge",
    "12 slot bags in 2008",
    "why are bags still this small",
    "profession bags when",
    "mining bag is a luxury",
    "herbs camped by bots",
    "nodes taken by 3 people",
    "skinning is a joke now",
    "leather is worthless",
    "ore is a war",
    "enchanting mats cost a kidney",
    "glyphs are a tax",
    "major glyph gold sink",
    "reforge when",
    "gems are a second job",
    "hit cap is a lifestyle",
    "expertise is a myth",
    "hit rating from the void",
    "this stat is fake",
    "spirit is a trap",
    "defense cap or die",
    "avoidance stacking pally",
    "block value warrior",
    "threat from gear not skill",
    "dps from gear not rotation",
    "rotation is 2 buttons",
    "this class is 1 button",
    "easy mode after the patch",
    "they nerfed the fun",
    "hotfixed into the ground",
    "ptr was a lie",
    "blue post copium",
    "ghostcrawler said its fine",
    "class is working as intended",
    "wai lmao",
    "intended means nerf",
    "buff notes then silent nerf",
    "patch day is a coin flip",
    "maintenance until your raid",
    "servers melting on reset",
    "tuesday reset tax",
    "lockout is a second job",
    "id extends forever",
    "saved to the wrong id",
    "trade a lockout",
    "alt raid is the real raid",
    "main is a bank now",
    "this toon is a mule",
    "need a boost im boosting",
    "powerleveling in the bg",
    "av farm till i die",
    "wg for the quest then out",
    "daily hub is a treadmill",
    "sons of hodir rep is a job",
    "argent grind is unpaid",
    "netherwing flashbacks",
    "sha'tari skyguard never again",
    "cenarion circle still",
    "timbermaw or nothing",
    "rep grind is the game",
    "exalted is a personality",
    "tabard is a flex",
    "title is a midlife crisis",
    "achieve points are fake",
    "glory of the raider when",
    "meta is a second raid",
    "mount from that achieve never",
    "drop chance is a rumor",
    "1 percent my foot",
    "rng is the raid leader",
    "parsed gray on purpose",
    "world first in my head",
    "server first in trade chat",
    "lying about naxx 40",
    "i was in bwl in 2006 sure",
    "rank 14 on this toon nuh uh",
    "glad in s1 on a mage",
    "arena points are a joke",
    "personal rating is pain",
    "2s with a random is a crime",
    "3s is a second marriage",
    "5s is a war crime",
    "skadi wipe again",
    "anub is a knockoff",
    "patchwerk is a tank check",
    "thaddius polarity my guys",
    "loatheb is a healer check",
    "sapph is a wipe machine",
    "kelthuzad mc the mage",
    "malygos phase 3 is a movie",
    "sarth 3d in a pug lmao",
    "algalon in this group no",
    "ymiron down the stairs",
    "ingvar yell is a jump scare",
    "kiting in halls of lightning",
    "loken is a push fight",
    "anomalus sparkles",
    "keristrasza freeze the pug",
    "nexus is a wet noodle",
    "uk is a corridor",
    "up is a surprise ogre",
    "gun'drak is a maze",
    "draktharon is a stairmaster",
    "culling is a movie",
    "hor is a corridor with feelings",
    "pit of saron is a walk",
    "forge of souls is short at least",
    "toc 5 is a waiting game",
    "trial of the champion rng",
    "violethold is a portal zoo",
    "oculus is a dragon tax",
    "nobody queues oculus",
    "i queued out of oculus",
    "random heroic gave oculus",
    "daily is oculus of course",
    "this game hates me",
    "rng hates this toon",
    "login lottery",
    "character stuck in a wall",
    "falling through the world",
    "got stuck in a texture",
    "uninstanced myself",
    "hearth from inside the floor",
    "trainer is upstairs of course",
    "class trainer in the worst spot",
    "weapon trainer closed",
    "riding trainer is a hike",
    "expert riding gold sink",
    "cold weather flying tax",
    "northrend flying is a wall",
    "cant fly here still",
    "dalaran sewers pvp",
    "underbelly is a gank box",
    "sewer rat pvp",
    "kras us arena",
    "ring of valor when",
    "nagrand arena flashbacks",
    "blade's edge is a pinball",
    "ruins of lordaeron is a box",
    "this bracket is 2 specs",
    "double dps 2s",
    "rasha + anything",
    "war + disc",
    "wls in every lobby",
    "team is a dampener",
    "resilience is a tax",
    "pvp gear in pve lmao",
    "pve gear in arena",
    "hit cap in the outdoor world",
    "i just want to quest",
    "ganked on a named spawn",
    "hour respawn named",
    "sharing the spawn like adults",
    "tagging wars",
    "grey mob from a runner",
    "he trained me on purpose",
    "leash is a suggestion",
    "reset is a myth",
    "evade bug classic",
    "immune to everything bug",
    "feign death worked nvm",
    "vanish broke",
    "blink into the pack",
    "charge off the platform",
    "death grip the trash",
    "army of the dead in town",
    "dk in every zone",
    "starting zone is dks",
    "dk starting zone is a movie",
    "worgen when",
    "goblin when",
    "next xpac will kill this",
    "cata will ruin the old world",
    "theyre gonna change the zones",
    "dont touch the barrens",
    "if they touch stv i quit",
    "vanilla zones were enough",
    "outland is a rock",
    "hellfire is a hallway",
    "nagrand is the pretty one",
    "terokkar is a nest",
    "zangar is a swamp tax",
    "netherstorm is a lag field",
    "shadowmoon is ugly on purpose",
    "blades is a canyon",
    "borean is a tundra",
    "howling is pretty at least",
    "grizzly is a forest tax",
    "zuldrak is a pyramid",
    "sholazar is ungoro 2",
    "storm peaks is a vertical tax",
    "icecrown is a raid hub",
    "crystalsong is a corridor",
    "wintergrasp is a parking lot",
    "this zone is a corridor",
    "this map is a hamster wheel",
    "quest density is a joke",
    "20 quests same camp",
    "kill 10 then 10 then 10",
    "collect 8 then 8 more",
    "escort at 40 percent hp",
    "npc walks into a pack",
    "escort died to a critter",
    "named npc leash is broken",
    "quest item didnt drop",
    "drop rate is a rumor",
    "the item is soulbound why",
    "unique quest item of course",
    "bag space for quest items",
    "quest log is full",
    "20 quest log in 2008",
    "abandon that one",
    "grey quests already",
    "this is green still",
    "orange quest in this zone",
    "im getting my face beaten",
    "level gap is a wall",
    "zone is the wrong level",
    "where do i go after this",
    "is this even the right zone",
    "i think im lost",
    "map is a suggestion",
    "minimap is a postage stamp",
    "tracking off on purpose",
    "find herbs off",
    "find minerals is a war",
    "nodes spawning under mobs",
    "herbs in the elite camp",
    "rich vein in a cave of death",
    "skin despawned",
    "loot rolled into the lava",
    "body despawned with my item",
    "i needed that grey",
    "vendor is a hike",
    "repair is in the other town",
    "ammo vendor closed",
    "reagents vendor is the wrong one",
    "poison vendor for 20 silver",
    "food is a second inventory",
    "water is a warlock tax",
    "mage food please",
    "table please",
    "summon a table",
    "healthstones please",
    "can i get a port",
    "port to shatt",
    "port to dal",
    "portal to nowhere",
    "wrong portal",
    "hearth is dal of course",
    "hearth is org i regret it",
    "bind in the inn that lags",
    "this general is a dumpster",
    "general never change",
    "who talks in general anyway",
    "i leave general on for this",
    "chat is the real game",
    "this is why i play",
    "cant pause an mmo",
    "raid warning in general lmao",
    "caps lock warrior",
    "macro spam",
    "gold spam report",
    "wts gold report",
    "phishing whispers",
    "free gold site sure",
    "i already reported him",
    "mass report that name",
    "silence incoming",
    "chat ban speedrun",
    "gms are asleep",
    "ticket in 2008 time",
    "unstuck when",
    "stuck in a chair",
    "cant sit this chair is a trap",
    "dalaran fountain is a religion",
    "coin in the fountain",
    "this is a slot machine",
    "i just want my mount",
    "invincible when",
    "asher next xpac",
    "rare spawn is a lifestyle",
    "time-lost proto is a rumor",
    "i have never seen it",
    "lucky loot in trade chat",
    "flexing in dalaran",
    "transmog when",
    "my gear is brown",
    "green until 70",
    "heirlooms in every slot",
    "rested bar is my personality",
    "double xp would ruin this",
    "random dungeon saved me",
    "random dungeon ruined pugs",
    "no more looking for group in town",
    "org was the lfg board",
    "ifn in chat was a skill",
    "pst for inv was a language",
    "lfm tank have summons",
    "need all have none",
    "geared mean i have a tabard",
    "achieve is not a skill",
    "ilvl is a personality",
    "scoreboard in a 5 man",
    "this is not a race",
    "pull when ready means pull",
    "food buff missing",
    "flask on trash",
    "cauldron please",
    "mage first",
    "int food",
    "str food on the caster",
    "wrong food on the tank",
    "this group cant read",
    "english please",
    "this is a us server nvm",
    "latency 300",
    "east coast ping",
    "west coast from eu",
    "this node is in australia",
    "packet loss simulator",
    "spell batching flashbacks",
    "vanilla batching was a sport",
    "i miss spell batching nuh uh",
    "charge on a delay",
    "overpower never procs",
    "deep wounds forever",
    "dots on a corpse",
    "wanding for 40 min",
    "this is a wand simulator",
    "i am a wand",
    "shadow priest is a dot bot",
    "affli is a spreadsheet",
    "destro is 1 button",
    "demo is a pet sit",
    "felguard pulling towns",
    "voidwalker tanking my mistakes",
    "succubus is a joke",
    "imp is a lamp",
    "this rotation is a drum loop",
    "i press 1 and 2",
    "wow is a 2 button mmo",
    "alt f4 the expansion",
    "this is a walking sim",
    "i paid to run",
    "subscription to jog",
    "15 a month to stand in fire",
    "the real boss is the grind",
    "delete your toon",
    "reroll already",
    "l2p noob",
    "l2p",
    "you play like a wet noodle",
    "your dps is grey",
    "sit down",
    "sit noob",
    "stay mad",
    "qq more",
    "cry is free",
    "get a job",
    "go outside",
    "your mom still tanks",
    "your mom has better parses",
    "boosted to 80 sit",
    "bought gold detected",
    "gold buyer lol",
    "heirlooms carrying you",
    "easy mode character",
    "fresh 80 sit down",
    "your gear is grey",
    "you were in bwl sure buddy",
    "glad in s1 lmao ok",
    "your arena team is a pug",
    "2s with your girlfriend",
    "shes carrying you",
    "open queue warrior detected",
    "parse merchant",
    "recount warrior",
    "you pull like a hunter",
    "you heal like a dps",
    "you tank like a mage",
    "afk or kick",
    "kick him",
    "hes the wipe",
    "you stood in it again",
    "move or die noob",
    "your rotation is 1 button and you still miss",
    "keyboard turner spotted",
    "clicker in melee",
    "backpedal champion",
    "wasd warrior",
    "you jump every pull",
    "stop talking",
    "who asked",
    "didnt ask",
    "your mom asked",
    "no u",
    "first",
    "this general",
    "who talks like this",
    "ok and",
    "found the pally",
    "found the hunter",
    "found the dk",
    "ok kid",
    "sit",
    "ez",
    "nub",
    "this is why you parse grey",
    "reroll pally",
    "reroll hunter",
    "delete that name",
    "name is a crime",
    "your guild is a joke",
    "pugs in this guild lmao",
    "your guild wipes on trash",
    "this server is dead",
    "pop is a joke",
    "transfer already",
    "dead server talking",
    "this realm is a graveyard",
    "ally biased server",
    "horde server confirmed",
    "reported",
    "report that name",
    "stfu",
    "stfu general",
    "youre bad",
    "youre not good",
    "he thinks hes good",
    "found the tryhard",
    "casual detected",
    "hardcore in a pug lmao",
    "go parse on the dummy",
    "dummy parsing in dalaran",
    "uninstall then stay",
    "close the game already",
    "alt f4 yourself",
    "why are you still here",
    "him again",
    "muted",
    "ignore list is full",
    "you type faster than you play",
    "chat warrior",
    "general pvp",
    "you lost",
    "owned",
    "pwned",
    "got em",
    "sit down kid",
    "bedtime",
    "school night",
    "your dps meter is a diary",
    "healer is watching youtube",
    "healer is on myspace",
    "alt tabbed in a pull",
    "afk at the keyboard",
    "bio in a boss pull",
    "this one types with elbows",
    "you need a guide for trash",
    "watch a strat then talk",
    "you pull like youre invincible",
    "bubble hearth detected",
    "vanish from the wipe classic",
    "you died first again",
    "rez this one last",
    "let him sit",
    "dont rez the hunter",
    "need on everything still",
    "greed is a foreign word to you",
    "ninja hands",
    "your bags are full of other peoples loot",
    "wts your dignity",
    "lf one player who can read",
    "english in chat please",
    "type slower youre embarrassing us",
    "caps lock is stuck",
    "calm down caps",
    "this is not ventrilo",
    "your mic is a blender",
    "push to talk exists",
    "you breathe like a dragon",
    "horde always wins av",
    "alliance always camps the fp",
    "tbc was better fight me",
    "vanilla was harder",
    "wrath is easy thats why you like it",
    "lfd ruined the game",
    "random dungeon made you lazy",
    "paladins need a nerf today",
    "dks shouldnt exist",
    "hunters arent a class",
    "warlocks in every lobby for a reason",
    "disc is broken and you know it",
    "resilience is a tax on fun",
    "your faction cant pvp",
    "org is uglier and you know it",
    "sw players cant play",
    "night elves are a fashion server",
    "undead look like the login screen",
    "trolls only exist for the jokes",
    "tauren is a joke model",
    "gnome paladin when",
    "blood elves ruined horde",
    "forsaken is the only race",
    "draenei is a space goat",
    "humans have no identity",
    "orcs only zug",
    "troll pvp is a cheat",
    "blood elf pally is a crime",
    "alliance has no pvp",
    "horde has no raids",
    "naxx is easy",
    "ulduar is the only real raid",
    "icc pugs already lmao",
    "voa is not content",
    "malygos is a movie not a fight",
    "sarth 3d in a pug no",
    "heroism on trash is a sin",
    "flask on trash or youre poor",
    "meters dont heal fight me",
    "watch a video then talk",
    "east coast ping forever",
    "west coast from eu lmao",
    "horde is better at pvp",
    "alliance wins because of paladins",
    "ret is a win button",
    "unholy is homework",
    "frost dk is a stun bot",
    "survival hunter is a myth",
    "mm is 1 button and proud",
    "affli is a spreadsheet class",
    "destro is a chaos bolt macro",
    "demo is a pet sitter",
    "arms is a queue simulator",
    "fury is spinning to win",
    "prot pally is a flashlight",
    "holy pally is a beacon bot",
    "disc is a bubble wrap",
    "holy priest is a sit simulator",
    "shadow is a dot bot",
    "ele is a shock bot",
    "enh is a casino",
    "resto sham is a totem farmer",
    "feral is a cat with extra steps",
    "boomkin is a moonfire turret",
    "resto druid is a hot blanket",
    "bear is a healthbar",
    "rogue is a stun lock with a person attached",
    "combat rogue is auto attack",
    "mut is a poison cloud",
    "sub is a ninja fantasy",
    "mage is a sheep with a fireball",
    "arcane is a mana battery",
    "fire is crit or afk",
    "frost is a slow walk",
    "warlock is a farm class",
    "your class is a homework assignment",
    "this spec is a tax",
    "hybrid tax is real",
    "pure dps is a crutch",
    "bring the player not the class nuh uh",
    "buffs win raids not you",
    "your raid is a buff bot",
    "10 man is the real game",
    "25 man is a zerg",
    "heroic is a pug filter",
    "normal is for learning you said",
    "this lockout is a second job",
    "reset day is a personality",
    "you only play reset",
    "casuals ruined raids",
    "hardcores ruined pugs",
    "gdkp is coming just wait",
    "loot council is friends",
    "dkp is a pyramid",
    "need rolling is a religion",
    "ml is on a power trip",
    "your raid lead is a spreadsheet",
    "vent is a courtroom",
    "this guild apps in trade",
    "socials in a raid slot",
    "your core is 3 people",
    "bench is the real roster",
    "you raid log",
    "log on for raid log off",
    "this is a login screen with extra steps",
    "pve vs pvp gear argument again",
    "resil in a raid lmao",
    "hit cap in the outdoor world why",
    "expertise is fake",
    "avoidance pally talking",
    "block value is a lifestyle",
    "spirit is a trap stat",
    "enchants cost more than the run",
    "glyphs are a gold sink on purpose",
    "reforge when blizz",
    "professions are a tax",
    "jwcs in every raid",
    "cook is a real profession fight me",
    "fishing is content",
    "your gather toon is your main",
    "bank alt has a better ui than you",
    "too many alts is a cry for help",
    "rested xp is carrying your account",
    "you ding and log like a coward",
    "xp per hour is a myth you chase",
    "daily hub is a hamster wheel",
    "sons of hodir can stay hated",
    "argent grind is a second job",
    "netherwing flashbacks i still have",
    "rep grind is the actual game",
    "exalted is a personality disorder",
    "tabard is not a flex",
    "achieve points are fake currency",
    "glory of the raider when never",
    "meta is a second raid id",
    "the mount from that achieve is a rumor",
    "1 percent drop my foot",
    "server first in trade chat sure",
    "lying about naxx 40 again",
    "personal rating is pain and you like it",
    "double dps 2s is a coin flip",
    "rasha plus anything",
    "war disc forever",
    "wls in every lobby still",
    "dampener is the real opponent",
    "pvp gear in pve is a statement",
    "pve gear in arena is a cry",
    "ganked on a named spawn again",
    "hour respawn named of course",
    "sharing the spawn like adults nvm",
    "tagging wars in this zone",
    "leash is a suggestion apparently",
    "your faction camps every quest npc",
    "world pvp is just ganking lowbies",
    "honor farming noobs still",
    "this bracket is dead and you know it",
    "wintergrasp when never",
    "wsg is a tunnel with extra flags",
    "eots is a meme battleground",
    "ab is a node simulator",
    "sota is a vehicle tax",
    "ioc is wintergrasp junior",
    "i died to a critter",
    "my pet is smarter than this pug",
    "the sheep sheeped me",
    "i just vendored my epic",
    "hearthstoned into combat",
    "i trained the whole cave to town",
    "gm can i have my gold back",
    "this npc walked into a wall",
    "i have been sitting in this chair for 20 min",
    "dalaran fountain took my gold",
    "i clicked the wrong portal",
    "summoning stone is a lie",
    "i just found the fp after 2 hours",
    "quest said kill 10 i killed 40",
    "the drop is 100% they said",
    "i disenchanted the wrong one",
    "sold the boe for 1 gold",
    "buyout was 1 copper lmao",
    "i just needrolled a grey",
    "loot went to the hunter of course",
    "i rezzed in the wrong graveyard",
    "ghost wolfed off a cliff",
    "blinked into the pack again",
    "charged off the platform",
    "death gripped the trash into me",
    "army of the dead in town again",
    "i just drowned at the fp",
    "i pulled with my face",
    "tanked with my teeth",
    "healed with a wand",
    "dpsed with a shield",
    "i just used a hearth on a corpse",
    "my bags sorted themselves into chaos",
    "i need a bag for my bags",
    "i just found goldshire by accident",
    "a mankrik walks into a bar",
    "goldshire inn is a nightclub",
    "theres a party in goldshire",
    "naked in goldshire of course",
    "erp in the inn again",
    "i just waved at a horde",
    "i just /spit a pally",
    "i just /chicken the hunter",
    "at least i have chicken",
    "i just trained the escort into a pack",
    "i accidentally the loot",
    "do not want",
    "im in ur base",
    "all your gold",
    "this is the song that never ends",
    "a paladin walks into naxx",
    "how much wood would a wood elf",
    "im not a gnome im a compact paladin",
    "rogues do it from behind",
    "warlocks have friends theyre demons",
    "hunter is a pet class with a player",
    "mages are glass and they like it",
    "priests fear themselves",
    "shaman totems are furniture",
    "druid is 4 classes in a trenchcoat",
    "dk is a death rattle",
    "pally bubble hearth classic",
    "bubble hearth is a lifestyle",
    "vanish is a personality",
    "ice block afk",
    "divine intervention the wipe",
    "heroism on the last add",
    "bloodlust was on cooldown",
    "this is fine",
    "i like turtles",
    "i just emoted in combat",
    "dance in org is the real raid",
    "sw fountain is a meeting",
    "ifht in chat was a language",
    "pst for inv was a skill",
    "i just /who the whole zone",
    "friends list is a graveyard",
    "guild bank ate my mats",
    "i just mailed myself",
    "wrong alt of course",
    "this toon is a mule with dreams",
    "i logged the wrong character",
    "spent 10 min in character select",
    "name already taken forever",
    "server is full nvm it isnt",
    "queue popped i was in the bathroom",
    "deserter is a lifestyle",
    "dungeon deserter because oculus",
    "i just hearthed from the entrance",
    "summoning 3 of 3 nvm 2",
    "click the stone i beg",
    "meeting stone unused as always",
    "i just accepted the wrong queue",
    "random heroic gave me a corridor",
    "this loading screen is my home now",
    "character stuck in a wall again",
    "falling through the world classic",
    "gms are collecting stamps",
    "i reported a squirrel",
    "this critter aggroed me",
    "a bee killed my mage",
    "dalaran sewers ate another noob",
    "i just got pickpocketed by a quest",
    "the escort walked into the ocean",
    "npc pathing is drunk",
    "fp pathing took me sightseeing",
    "i missed the zep again",
    "org is a maze on purpose",
    "geared means i have a tabard",
    "scoreboard in a 5 man why",
    "food buff missing of course",
    "str food on the caster classic",
    "int food please i beg",
    "flask on trash he said",
    "i just wasted a cauldron on trash",
    "reagents cost more than the boss",
    "i am out of shards",
    "healthstone is a myth in this group",
    "soulstone the wipe",
    "ankh used on trash",
    "innervate the dps",
    "misdirect into the pack classic",
    "succubus is a joke pet",
    "feed your pet i beg",
    "out of ammo mid boss",
    "wanding the boss like 2006",
    "and sometimes i press 3",
    "my rotation is a drum loop",
    "this game is a tuesday",
    "character list is a loading screen",
    "i just paid to stand in fire",
    "15 a month to jog",
    "subscription to walk",
    "im losing to a quest log",
    "macro spam in general",
    "this is a waiting room",
    "ready check for trash",
    "food for a patrol",
    "i just buffed the wall",
    "reapplied fort 8 times",
    "mark the skull i beg",
    "skull is a suggestion",
    "traps are decorative",
    "stuns on cooldown forever",
    "interrupts are a myth",
    "kick exists you know",
    "someone spellsteal the buff",
    "dispell the wrong thing",
    "cleanse the tank of armor",
    "i just purged the food buff",
    "leeroy jenkins",
    "more dots",
    "the cake is a lie",
    "all your base",
    "its over 9000",
    "this is sparta",
    "do a barrel roll",
    "i accidentally the whole",
    "chuck norris doesnt quest",
    "chuck norris hit cap is 0",
    "thats what she said",
    "yo mama so fat she needs 2 accounts",
    "yo mama so poor she rolls need on greys",
    "thunderfury thunderfury thunderfury",
    "wts thunderfury",
    "time lost proto is a rumor",
    "mankriks wife when",
    "still looking for marvin",
    "marvin the scarbeetle",
    "pew pew",
    "zug zug",
    "for the horde",
    "for the alliance",
    "lok tar",
    "lok tar ogar",
    "your argument is invalid",
    "epic fail",
    "fail",
    "win",
    "epic win",
    "your face",
    "your mom",
    "anal",
    "goldshire rp",
    "lf girlfriend in goldshire",
    "wts horse",
    "imma firin mah lazor",
    "all your base are belong to us",
    "you have no chance to survive",
    "move zigzag",
    "its a trap",
    "i am your father",
    "use the force",
    "these arent the drops youre looking for",
    "thats no moon",
    "i find your lack of dps disturbing",
    "do or do not there is no try",
    "winter is coming to northrend",
    "one does not simply walk into icecrown",
    "my precious drop",
    "you shall not pass this trash",
    "second breakfast after this grind",
    "i see dead people in this pug",
    "heres johnny in the ogre room",
    "houston we have a wipe",
    "im the king of the world azeroth",
    "say hello to my little felguard",
    "i ll be back after this wipe",
    "hasta la vista baby",
    "i need a weapon said every warrior",
    "get to the chopper the zep",
    "inconceivable this pug",
    "nobody expects the inquisition in sm",
    "its just a flesh wound",
    "run away",
    "ni",
    "we are the knights who say ni",
    "bring out yer dead",
    "im not dead yet",
    "this parrot is no more",
    "its only a model",
    "happy feet in dalaran",
    "trololol",
    "trololo",
    "problem",
    "trollface in general",
    "forever alone in lfg",
    "not sure if lag or dps",
    "y u no interrupt",
    "y u no kick",
    "i can has mount",
    "i can has epic",
    "do not want this spec",
    "rickroll incoming",
    "never gonna give you up",
    "never gonna let you down this pug",
    "its peanut butter jelly time",
    "leeroy",
    "jenkins",
    "at least i have chicken still",
    "more dots more dots",
    "the numbers mason",
    "what are the numbers",
    "pc load letter",
    "someone set us up the bomb",
    "you are on the way to destruction",
    "ha ha ha ha",
    "take off every zig",
    "for great justice",
    "move zig",
    "you have no chance to survive make your time",
    "all your gold are belong to ah",
    "i accidentally the whole bag",
    "i accidentally the boss",
    "do a barrel roll in oculus",
    "rip in peace",
    "gg ez",
    "gg wp uninstall",
    "behind you",
    "my bad the wipe",
    "sorry not sorry",
    "it was the lag",
    "it was the pet",
    "it was the hunter",
    "blame the pally",
    "blame the dk",
    "blame blizz",
    "blizz did this",
    "ghostcrawler when",
    "blue post incoming",
    "working as intended",
    "raid logger",
    "pug only",
    "always qqing",
    "subscription talking",
    "15 a month",
    "blizz thanks",
    "nerf soon",
    "buff never",
    "ptr copium",
    "have fun with that",
    "good luck uninstall",
    "glhf",
    "glhf uninstall",
    "see you in org",
    "see you in the ticket",
    "gm is typing",
    "silence speedrun",
    "chat log saved",
    "barrens energy",
    "goldshire moment",
    "stv moment",
    "classic",
    "peak wrath",
    "never change general",
    "who even talks in here",
    "general is a mess",
    "language",
    "gm pls",
    "take it to the forums",
    "right click",
    "mute and move on",
    "so aids",
    "10/10",
    "blizz pls nerf",
    "who designed this",
    "do it naked",
    "skip it",
    "they made it worse",
    "its a classic",
    "tell me about it",
    "oof yeah",
    "true true",
    "wait no",
    "ok pally",
    "ok hunter",
    "ok dk",
    "ok mage",
    "touch the quest log",
    "go quest",
    "go outside wait",
    "found the carebear",
    "found the ninja",
    "found the parse merchant",
    "found the gold buyer",
    "found the boost",
    "boosted hands",
    "heirloom baby",
    "dk baby",
    "fresh 80 energy",
    "grey parsing with confidence",
    "meters in a 5 man lmao",
    "recount is your personality",
    "you inspect everyone",
    "inspecting me wont help you",
    "gearscore when nvm",
    "gs is a fake number",
    "your gs is a suggestion",
    "achieves in the app",
    "your app is a novel",
    "loot council friends again",
    "boosted to 80 talking",
    "daily then log like a coward",
    "ganked for existing",
    "lowbies getting farmed still",
    "world pvp is dead fight me",
    "this xpac is easy fight me",
    "they dumbed it down fight me",
    "wrath is faceroll and you like it",
    "borean is a tundra tax",
    "blades edge is a pinball",
};

// 223 argument / joke / trash replies
inline char const* const kDribbleBounces[] = {
    "lmao",
    "this",
    "so true",
    "blizz pls",
    "qq",
    "same",
    "cry more",
    "l2p",
    "nub",
    "ez",
    "this is why pugs suck",
    "and yet here you are",
    "keep telling yourself that",
    "no argument",
    "lol same",
    "oof",
    "not wrong",
    "yeah they suck",
    "i hate those",
    "uninstall then",
    "close the game",
    "get good",
    "ok kid",
    "sit",
    "stay mad",
    "found the pally",
    "ok and",
    "first time",
    "who even talks in here",
    "general is a mess",
    "never change",
    "reported",
    "report that",
    "language",
    "gm pls",
    "take it to the forums",
    "found the qq",
    "+1",
    "already reported",
    "for what lmao",
    "calm down",
    "right click",
    "mute and move on",
    "so aids",
    "10/10",
    "blizz pls nerf",
    "who designed this",
    "do it naked",
    "skip it",
    "they made it worse",
    "its a classic",
    "tell me about it",
    "oof yeah",
    "true true",
    "wait no",
    "ok pally",
    "ok hunter",
    "ok dk",
    "ok mage",
    "touch the quest log",
    "go quest",
    "go outside wait",
    "subscription talking",
    "15 a month",
    "blizz thanks",
    "working as intended",
    "wai",
    "nerf soon",
    "buff never",
    "ptr copium",
    "blue post incoming",
    "ghostcrawler when",
    "raid logger",
    "pug only",
    "always qqing",
    "have fun with that",
    "good luck",
    "glhf uninstall",
    "see you in org",
    "see you in the ticket",
    "gm is typing",
    "silence speedrun",
    "chat log saved",
    "barrens energy",
    "goldshire moment",
    "stv moment",
    "classic",
    "peak wrath",
    "never change general",
    "who asked",
    "didnt ask",
    "no u",
    "your mom",
    "your face",
    "first",
    "owned",
    "pwned",
    "fail",
    "epic fail",
    "win",
    "thats what she said",
    "more dots",
    "leeroy",
    "at least i have chicken",
    "the cake is a lie",
    "uninstall wow pls",
    "l2p noob",
    "sit noob",
    "reroll",
    "delete your toon",
    "qq more",
    "cry is free",
    "stfu",
    "ok and what",
    "found the noob",
    "found the ninja",
    "found the dk",
    "found the hunter",
    "found the carebear",
    "fight me",
    "prove it",
    "source",
    "you wish",
    "in your dreams",
    "keep crying",
    "bedtime",
    "school night",
    "get a job",
    "go outside",
    "touch the keyboard",
    "he thinks hes good",
    "parse merchant",
    "meters talking",
    "vent is that way",
    "take it to vent",
    "this is general",
    "wrong channel",
    "trade is that way",
    "lfg is dead anyway",
    "goldshire is that way",
    "erp is that way",
    "for the horde",
    "for the alliance",
    "zug zug",
    "pew pew",
    "ni",
    "run away",
    "im not dead yet",
    "its a trap",
    "y u no",
    "problem",
    "trololo",
    "gg ez",
    "gg wp",
    "rip",
    "my bad",
    "blame the hunter",
    "blame the pally",
    "blame blizz",
    "it was the lag",
    "it was the pet",
    "not my wipe",
    "i pulled on purpose",
    "big pull energy",
    "do it naked then",
    "say it to my face",
    "whisper me coward",
    "pst me then",
    "your guild talking",
    "your main is an alt",
    "boosted hands",
    "heirloom baby",
    "dk baby",
    "fresh 80 sit",
    "grey parse with confidence",
    "inspect me i dare you",
    "gs is fake",
    "naxx 40 sure buddy",
    "glad in s1 nuh uh",
    "vanilla was better nuh uh",
    "tbc was better nuh uh",
    "wrath is easy and",
    "lfd ruined you",
    "carebear detected",
    "tryhard detected",
    "casual detected",
    "hardcore in general lmao",
    "lol",
    "lmao ok",
    "sure buddy",
    "ok",
    "k",
    "mhm",
    "uh huh",
    "whatever",
    "found him",
    "there it is",
    "called it",
    "knew it",
    "every time",
    "goldshire energy",
    "wrong window",
    "chat is the game",
    "why we play",
    "reported for being right",
    "reported for facts",
    "gm is laughing",
    "ticket written",
    "silence incoming",
    "enjoy the mute",
    "ignore list calling",
    "muted",
    "next topic",
    "moving on",
    "anyway",
    "so anyway",
    "anyway uninstall",
    "close it",
    "alt f4",
    "log off",
    "see ya",
    "bye then",
    "dont let the fp hit you",
};

// Compound takes. Mix with the short punches so General is not all 3-word lines.
inline char const* const kDribbleLongTakes[] = {
    "is the lag getting worse or did everyone just log on at once again",
    "dks took every tank spot and half the dps spots as usual",
    "lfm icc 25 need 24 and a rl who doesnt pull on ready",
    "server pop so low i can hear the ah crickets in dalaran",
    "gold sellers in trade every 30 seconds gms asleep again",
    "alliance queue is a joke horde bias confirmed",
    "who actually likes toc be honest",
    "flying in northrend was a mistake and i will die on this hill",
    "arthas did nothing wrong",
    "this economy more inflated than a prot pally threat meter",
    "remember when warriors could still tank without a dk taking the spot",
    "pallys still the most annoying class in every xpac change my mind",
    "why does every pug wipe on saurfang like its a surprise",
    "is there a single hunter who doesnt stand in fire",
    "why is every tank a dk who thinks death grip is a personality",
    "trade chat is just gold ads and people begging for carries",
    "lfm ulduar 10 need people who have actually seen the bosses",
    "icc trash hits harder than the bosses",
    "another pally flashing wings in dalaran like anyone asked",
    "gms online only when someone reports a gold seller",
    "remember when people used to talk in general instead of just lf boost",
    "toc so boring i fell asleep on the champion and still got loot",
    "every pug healer is a disc priest who forgot they have a shield",
    "why do people still roll on tokens they cant even use",
    "northrend flying made the world feel empty and i stand by that",
    "lfm naxx 25 need 23 and a tank who doesnt die to patchwerk",
    "gold inflation so bad 100g feels like 10g used to",
    "if ur gonna afk in dalaran at least stop blocking the portal",
    "if ur buying gold just say so the wts icc carry posts aint fooling anyone",
    "rdf when asking for the 19 people still running heroics the old way",
    "been a while since the last this server is dying post we overdue",
    "this server dies every sunday night like clockwork",
    "shoutout to the warrior who charged off the platform in icc",
    "shoutout to the rogue who vanish opened on the raid lead",
    "who keeps inviting the hunter that stands in every void zone",
    "lfm toc 25 need a group that can stay awake",
    "voa is a loot pinata and pugs still wipe on it",
    "nobody queues oculus and i dont blame them",
    "heroic daily is a second job at this point",
    "wg is a zerg fest and the queue is a coin flip"
};

// Stay on the claim. Used when the last line is an argument, not a one-liner pile-on.
inline char const* const kClaimExpansion[] = {
    "tbc was the whole game", "vanilla was harder", "wrath is easy and you like it",
    "lfd ruined pugs", "they dumbed it down", "ulduar is one raid",
    "you didnt even play tbc", "naxx 40 was a zoo nvm it was peak",
    "icc pugs already lmao", "this xpac is a log in button",
    "kara was a raid not a pug", "sunwell was actually hard",
    "wrath is a quest hub with a raid", "you like it because its easy",
    "tbc attunements were the game", "no flying in tbc was the point",
    "outland sucked and tbc was still better", "wotlk is a catchup xpac",
    "they added lfd because nobody could find groups", "heroics in tbc meant something",
    "naxx 10 is a joke compared to naxx 40", "you logged tbc on a mage sure",
    "vanilla had soul", "they sanded the edges off on purpose"
};
inline char const* const kClaimDk[] = {
    "dks shouldnt exist", "death grip is a personality", "unholy is homework",
    "frost dk is a stun bot", "starting zone is dks", "reroll warrior",
    "easy mode after 55", "every tank is a dk", "dk baby",
    "blood is a healthbar", "army of the dead in town again",
    "they gave them a tank spec for free", "death grip the tank next",
    "unholy is a pet class", "frost in every 2s lobby",
    "how is that a starting class", "dk in every zone",
    "they skipped 55 levels and still parse", "anti magic shell and a prayer",
    "bone shield is a crutch", "your ghoul is smarter than you"
};
inline char const* const kClaimPally[] = {
    "ret is a win button", "bubble hearth classic", "found the pally",
    "wings in dalaran again", "prot pally is a flashlight", "holy is a beacon bot",
    "nerf paladins already", "ok pally", "alliance wins because of paladins",
    "blessings are the whole spec", "bubble then wings then cry",
    "consecration is aoe for people who cant aim", "hand of salvation the parse",
    "ret is 2 buttons and a hammer", "holy pally is a sit simulator",
    "prot pally never dies and never tanks", "divine plea in a pug lmao",
    "youre a walking buff bot", "judgement of light carrying the raid",
    "retribution is a pvp spec in pve", "seal twisting flashbacks"
};
inline char const* const kClaimHunter[] = {
    "hunters arent a class", "stand in fire challenge failed", "feed your pet",
    "misdirect into the pack", "out of ammo mid boss", "pet pulling towns",
    "need rolling hunters", "mm is 1 button and proud",
    "survival is a trap macro", "bm is a pet with a person attached",
    "feign death worked nvm", "you pulled with the pet on purpose",
    "traps on cooldown forever", "volley the whole room",
    "hunters need on every bow", "your pet has better threat",
    "aspect of the cheetah into a daze", "steady shot simulator",
    "you afk between shots", "mark the skull i beg"
};
inline char const* const kClaimRaid[] = {
    "watch a video then talk", "this is a 5 man not icc", "saurfang is a tank check",
    "patchwerk is still a wall", "toc is a waiting room", "nobody interrupts",
    "wipe on trash again", "heroism on trash is a sin",
    "ulduar people cant jump", "malygos is a movie", "algalon in this pug no",
    "voa is a loot pinata", "naxx pugs are a zoo", "stack means spread here",
    "move out of the swirl", "first boss took 12 min",
    "ready check for trash", "food for a patrol", "flask on trash he said",
    "this lockout is a second job", "logs dont matter in a pug"
};
inline char const* const kClaimFaction[] = {
    "horde always wins av", "alliance always camps", "your faction cant pvp",
    "queue bias is real", "org is uglier and you know it", "sw players cant play",
    "world pvp is just ganking lowbies", "stv is gank city",
    "if youre in stv you deserve it", "tarren mill vs southshore forever",
    "ally has paladins thats the whole pvp", "horde q is instant because youre all on",
    "wg is a zerg fest", "eots is a meme", "wsg tunnel vision",
    "av is 40 mins of running", "your fp is a campfire", "lowbies getting farmed still"
};
inline char const* const kClaimFlying[] = {
    "the world felt bigger on a gryphon", "northrend is a hamster wheel now",
    "flying was a mistake", "i stand by that", "cold weather flying tax",
    "you just skip the zone", "no mounts till 30 still hurts",
    "why is walking still a thing", "northrend flying is a wall",
    "you fly over the quests then complain xp is slow",
    "outland flying was enough", "the map is a loading screen with a mount",
    "storm peaks is a vertical tax", "cant fly here still"
};
inline char const* const kClaimGold[] = {
    "ah is a casino", "100g is the new 10g", "gold sellers in mail",
    "wts icc carry sure buddy", "repair bill hates me", "emblem inflation",
    "glyphs are a tax", "flying is a gold sink", "mount gold is a trap",
    "trade is a gold spam", "ah is a scam", "1 copper drops lmao",
    "you bought gold just say so", "repair after one wipe",
    "enchanting mats cost a kidney", "badges are a grind"
};
inline char const* const kClaimGeneric[] = {
    "prove it", "nuh uh", "you wish", "keep telling yourself that",
    "no argument", "and you know it", "fight me", "source",
    "not even close", "wrong", "ok and", "stay mad",
    "thats a take", "weak", "try again", "not how it went",
    "you werent there", "rewrite history somewhere else",
    "lmao no", "hard no", "absolutely not", "in your dreams"
};

#endif
